groups:
- name: application_alerts
  rules:
  - alert: HighCPUUsage
    expr: process_cpu_usage > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High CPU usage detected
      description: CPU usage is above 80% for 5 minutes

  - alert: HighMemoryUsage
    expr: sum(jvm_memory_used_bytes) / sum(jvm_memory_max_bytes) > 0.85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High memory usage detected
      description: Memory usage is above 85% for 5 minutes

  - alert: HighResponseTime
    expr: http_server_requests_seconds_max > 2
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High response time detected
      description: Maximum response time is above 2 seconds for 5 minutes

  - alert: HighErrorRate
    expr: sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) / sum(rate(http_server_requests_seconds_count[5m])) > 0.05
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: High error rate detected
      description: Error rate is above 5% for 5 minutes

  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: Instance down
      description: "{{ $labels.instance }} has been down for more than 5 minutes"

  - alert: DatabaseConnectionPoolSaturation
    expr: hikaricp_connections_active / hikaricp_connections_max > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Database connection pool near saturation
      description: Database connection pool is above 80% capacity for 5 minutes

  - alert: RedisConnectionFailure
    expr: redis_up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: Redis connection failure
      description: Redis connection has been down for more than 5 minutes

  - alert: MongoDBConnectionFailure
    expr: mongodb_up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: MongoDB connection failure
      description: MongoDB connection has been down for more than 5 minutes
