# Production Configuration for Render + Vercel
spring:
  # Production database configuration
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      auto-index-creation: true

# Production server configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/jpeg,image/png,image/webp,image/gif
    min-response-size: 1024

# CORS configuration for Vercel frontend
app:
  cors:
    allowed-origins: ${FRONTEND_URL:https://your-vercel-app.vercel.app}
    max-age: 3600

# Logging configuration for production
logging:
  level:
    root: WARN
    com.ecommerce: INFO
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"