spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${APP_URL}/api/auth/oauth2/callback/google

server:
  port: ${PORT:8080}
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEYSTORE_PATH:}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:}
    key-store-type: ${SSL_KEYSTORE_TYPE:PKCS12}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.ecommerce: ${LOG_LEVEL:INFO}
  file:
    name: ${LOG_FILE_PATH:/var/log/ecommerce/application.log}
    max-size: 10MB
    max-history: 30

app:
  cors:
    allowed-origins: ${FRONTEND_URL}
  security:
    rate-limiting:
      enabled: ${RATE_LIMIT_ENABLED:true}
      requests: ${RATE_LIMIT_REQUESTS:100}
      window: ${RATE_LIMIT_WINDOW:60}
  upload:
    max-file-size: ${MAX_FILE_SIZE:5MB}
    directory: ${UPLOAD_DIR:/var/ecommerce/uploads}