spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/ecommerce}
      database: ${SPRING_DATA_MONGODB_DATABASE:ecommerce}
  
  web:
    resources:
      static-locations: file:/app/Products/
  
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:https://your-vercel-app.vercel.app,http://localhost:3000,http://localhost:5173}

logging:
  level:
    com.ecommerce: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"