spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      auto-index-creation: true
  
  redis:
    enabled: false
  
  session:
    store-type: none

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: your_dev_jwt_secret_key
  expiration: 86400000
  refresh-token:
    expiration: 604800000

app:
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type,X-Requested-With
    exposed-headers: Authorization
    allow-credentials: true
    max-age: 3600

logging:
  level:
    root: INFO
    com.ecommerce: DEBUG
    org.springframework.data.mongodb: DEBUG
